// Generated by Selenium IDE
import org.junit.Test;

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestDisponibilidad {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testDisponibilidad() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    //Iniciamos sesión con un usuario anteriormente registrado con email hugo@gmail.com
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("hugo@gmail.com");
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("1234");
    driver.findElement(By.cssSelector(".loginEnter")).click();
    driver.findElement(By.id("logotipo")).click();
    driver.findElement(By.cssSelector(".botonDisponibilidadFecha:nth-child(1)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".botonDisponibilidadFecha:nth-child(1)"));
      dropdown.findElement(By.xpath("//option[. = '10']")).click();
      //Elegimos que este disponible desde el dia 10
    }
    driver.findElement(By.cssSelector(".Desde > .botonDisponibilidadFecha:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".Desde > .botonDisponibilidadFecha:nth-child(2)"));
      dropdown.findElement(By.xpath("//option[. = '5']")).click();
    //Elegimos que este disponible desde el mes 5
    }
    driver.findElement(By.cssSelector(".Hasta > .botonDisponibilidadFecha:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".Hasta > .botonDisponibilidadFecha:nth-child(2)"));
      dropdown.findElement(By.xpath("//option[. = '12']")).click();
    //Elegimos que este disponible hasta el dia 12
    }
    driver.findElement(By.cssSelector(".Hasta > .botonDisponibilidadFecha:nth-child(3)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".Hasta > .botonDisponibilidadFecha:nth-child(3)"));
      dropdown.findElement(By.xpath("//option[. = '5']")).click();
    //Elegimos que este disponible hasta el mes 5
    }
    driver.findElement(By.id("BotonFiltrarDisponibilidad")).click();
    //Filtramos por estos datos
    driver.findElement(By.cssSelector("a:nth-child(2) img")).click();
    driver.findElement(By.cssSelector(".boton:nth-child(2) > b")).click();
  }
  
  //Podemos observar que de las 7 herramientas en un principio disponibles, tras aplicar el filtro
  //solo nos aparecen 5, que en este caso comprobamos que son las herramientas disponiles entre el 10/5/2023
  // y el 12/5/2023
}
