// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestInicioSesion {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: Test1
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:3000/ |  | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1552x840 |  | 
    driver.manage().window().setSize(new Dimension(1552, 840));
    // 3 | click | id=logotipo |  | 
    driver.findElement(By.id("logotipo")).click();
    // 4 | click | css=.boton:nth-child(1) > b |  | 
    driver.findElement(By.cssSelector(".boton:nth-child(1) > b")).click();
    // 5 | click | css=.boton:nth-child(2) > b |  | 
    driver.findElement(By.cssSelector(".boton:nth-child(2) > b")).click();
    // 6 | click | css=input:nth-child(1) |  | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 7 | click | css=input:nth-child(1) |  | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 8 | doubleClick | css=input:nth-child(1) |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("input:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 9 | click | css=a:nth-child(2) > .boton |  | 
    driver.findElement(By.cssSelector("a:nth-child(2) > .boton")).click();
    // 10 | mouseOver | css=a:nth-child(2) > .boton |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(2) > .boton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | mouseOut | css=a:nth-child(2) > .boton |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 12 | click | css=input:nth-child(1) |  | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    //Introducimos los datos del nuevo usuario
    // 13 | type | css=input:nth-child(1) | paula | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("paula");
    // 14 | click | css=input:nth-child(1) |  | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 15 | type | css=input:nth-child(1) | paula1@gmail.com | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("paula1@gmail.com");
    // 16 | type | css=input:nth-child(2) | Paula | 
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("Paula");
    // 17 | type | css=input:nth-child(3) | 666444555 | 
    driver.findElement(By.cssSelector("input:nth-child(3)")).sendKeys("666444555");
    // 18 | type | css=input:nth-child(4) | Avenida de la Complutense, 30 | 
    driver.findElement(By.cssSelector("input:nth-child(4)")).sendKeys("Avenida de la Complutense, 30");
    // 19 | type | css=input:nth-child(5) | paula1@paypal.com | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).sendKeys("paula1@paypal.com");
    // 20 | click | css=input:nth-child(6) |  | 
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    // 21 | type | css=input:nth-child(6) | C:\fakepath\Usuario.jpg | 
    driver.findElement(By.cssSelector("input:nth-child(6)")).sendKeys("C:\\fakepath\\Usuario.jpg");
    // 22 | click | css=button:nth-child(8) |  | 
    driver.findElement(By.cssSelector("button:nth-child(8)")).click();
    // 23 | click | css=input:nth-child(9) |  | 
    driver.findElement(By.cssSelector("input:nth-child(9)")).click();
    // 24 | click | css=input:nth-child(9) |  | 
    driver.findElement(By.cssSelector("input:nth-child(9)")).click();
    // 25 | doubleClick | css=input:nth-child(9) |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("input:nth-child(9)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 26 | type | css=input:nth-child(9) | 12345 | 
    driver.findElement(By.cssSelector("input:nth-child(9)")).sendKeys("12345");
    // 27 | click | css=input:nth-child(10) |  | 
    driver.findElement(By.cssSelector("input:nth-child(10)")).click();
    // 28 | doubleClick | css=input:nth-child(10) |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("input:nth-child(10)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 29 | doubleClick | css=input:nth-child(10) |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("input:nth-child(10)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 30 | type | css=input:nth-child(10) | 12345 | 
    driver.findElement(By.cssSelector("input:nth-child(10)")).sendKeys("12345");
    // 31 | click | css=.registerSignIn |  | 
    driver.findElement(By.cssSelector(".registerSignIn")).click();
    // 32 | click | css=input:nth-child(1) |  | 
    //Ahora iniciamos sesión con el usuario que hemos creado
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 33 | type | css=input:nth-child(1) | paula1@gmail.com | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("paula1@gmail.com");
    // 34 | click | css=input:nth-child(2) |  | 
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    // 35 | type | css=input:nth-child(2) | 12345 | 
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("12345");
    // 36 | click | css=.loginEnter |  | 
    driver.findElement(By.cssSelector(".loginEnter")).click();
    // 37 | click | css=.loginSubirDashboard |  | 
    
    //Hemos iniciado sesión sin ningún fallo
    
    driver.findElement(By.cssSelector(".loginSubirDashboard")).click();
    // 38 | click | css=.inputsforms |  | 
    driver.findElement(By.cssSelector(".inputsforms")).click();
    // 39 | click | css=.inputsforms |  | 
    driver.findElement(By.cssSelector(".inputsforms")).click();
    // 40 | click | css=input:nth-child(1) |  | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 41 | click | css=input:nth-child(1) |  | 
    //Creamos una nueva herramienta rellenando los campos
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 42 | type | css=input:nth-child(1) | Herramienta de crimpado | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("Herramienta de crimpado");
    // 43 | type | css=input:nth-child(2) | Taladro | 
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("Taladro");
    // 44 | click | css=select |  | 
    driver.findElement(By.cssSelector("select")).click();
    // 45 | select | css=select | label=Regular | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector("select"));
      dropdown.findElement(By.xpath("//option[. = 'Regular']")).click();
    }
    // 46 | click | css=input:nth-child(4) |  | 
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    // 47 | type | css=input:nth-child(4) | 4 | 
    driver.findElement(By.cssSelector("input:nth-child(4)")).sendKeys("4");
    // 48 | click | css=input:nth-child(5) |  | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).click();
    // 49 | click | css=input:nth-child(5) |  | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).click();
    // 50 | doubleClick | css=input:nth-child(5) |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("input:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 51 | click | css=input:nth-child(5) |  | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).click();
    // 52 | click | css=input:nth-child(5) |  | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).click();
    // 53 | type | css=input:nth-child(5) | Le quedan dos telediarios | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).sendKeys("Le quedan dos telediarios");
    // 54 | click | css=input:nth-child(6) |  | 
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    // 55 | click | id=registro |  | 
    driver.findElement(By.id("registro")).click();
    // 56 | type | css=input:nth-child(5) | Muy usada | 
    driver.findElement(By.cssSelector("input:nth-child(5)")).sendKeys("Muy usada");
    // 57 | click | css=input:nth-child(6) |  | 
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    // 58 | type | css=input:nth-child(6) | C:\fakepath\Herramienta2.jpg | 
    driver.findElement(By.cssSelector("input:nth-child(6)")).sendKeys("C:\\fakepath\\Herramienta2.jpg");
    // 59 | click | css=button:nth-child(8) |  | 
    driver.findElement(By.cssSelector("button:nth-child(8)")).click();
    // 60 | click | css=.loginEnter |  | 
    driver.findElement(By.cssSelector(".loginEnter")).click();
  }
  
  //Hemos podido registrar al nuevo usuario, iniciar sesión con su cuenta y ese usuario ha podido subir una nueva herramienta a la plataforma
}
