// Generated by Selenium IDE
// Autores: Abril y Jorge
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestFiltrados {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test3() {
    // Test name: Test3
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:3000/ |  | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1552x840 |  | 
    driver.manage().window().setSize(new Dimension(1552, 840));
    // 3 | click | css=input:nth-child(3) |  | 
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    // 4 | type | css=input:nth-child(3) | 10 | 
    driver.findElement(By.cssSelector("input:nth-child(3)")).sendKeys("10");
    // 5 | click | css=button:nth-child(4) |  | 
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    // 6 | click | css=a:nth-child(2) img |  | 
    driver.findElement(By.cssSelector("a:nth-child(2) img")).click();
    // 7 | click | id=logotipo |  | 
    driver.findElement(By.id("logotipo")).click();
    // 8 | click | id=filtroPrecio |  | 
    driver.findElement(By.id("filtroPrecio")).click();
    // 9 | type | id=filtroPrecio | 3 | 
    driver.findElement(By.id("filtroPrecio")).sendKeys("3");
    // 10 | click | id=botonFiltroPrecio |  | 
    driver.findElement(By.id("botonFiltroPrecio")).click();
    // 11 | click | css=a:nth-child(4) img |  | 
    driver.findElement(By.cssSelector("a:nth-child(4) img")).click();
    // 12 | runScript | window.scrollTo(0,1541.5999755859375) |  | 
    js.executeScript("window.scrollTo(0,1541.5999755859375)");
    // 13 | click | id=logotipo |  | 
    driver.findElement(By.id("logotipo")).click();
    // 14 | click | id=selectorCategorias |  | 
    driver.findElement(By.id("selectorCategorias")).click();
    // 15 | select | id=selectorCategorias | label=Silicona | 
    {
      WebElement dropdown = driver.findElement(By.id("selectorCategorias"));
      dropdown.findElement(By.xpath("//option[. = 'Silicona']")).click();
    }
    // 16 | click | css=.tarjeta img |  | 
    driver.findElement(By.cssSelector(".tarjeta img")).click();
    // 17 | click | id=logotipo |  | 
    driver.findElement(By.id("logotipo")).click();
    // 18 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 19 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 20 | doubleClick | id=filtroNombre |  | 
    {
      WebElement element = driver.findElement(By.id("filtroNombre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 21 | type | id=filtroNombre | Sierra | 
    driver.findElement(By.id("filtroNombre")).sendKeys("Sierra");
    // 22 | click | css=#botonfiltroNombre > b |  | 
    driver.findElement(By.cssSelector("#botonfiltroNombre > b")).click();
    // 23 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 24 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 25 | doubleClick | id=filtroNombre |  | 
    {
      WebElement element = driver.findElement(By.id("filtroNombre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 26 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 27 | type | id=filtroNombre | Destornillador estrella | 
    driver.findElement(By.id("filtroNombre")).sendKeys("Destornillador estrella");
    // 28 | click | css=#botonfiltroNombre > b |  | 
    driver.findElement(By.cssSelector("#botonfiltroNombre > b")).click();
    // 29 | click | id=logotipo |  | 
    driver.findElement(By.id("logotipo")).click();
    // 30 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 31 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 32 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 33 | doubleClick | id=filtroNombre |  | 
    {
      WebElement element = driver.findElement(By.id("filtroNombre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 34 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 35 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
    // 36 | doubleClick | id=filtroNombre |  | 
    {
      WebElement element = driver.findElement(By.id("filtroNombre"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 37 | click | id=filtroNombre |  | 
    driver.findElement(By.id("filtroNombre")).click();
  }
}
